version: '3'
services:
  redis-slave:
    container_name: "redis-slave"
    image: redis
    ports:
      - "6380:6379"
    command: "redis-server /etc/redis-config/redis.conf"
    volumes:
      - "./data/slave:/data/"
      - "./config/redis-slave:/etc/redis-config"
 